CREATE DATABASE "moviestars2.0"
    WITH 
    OWNER = postgres
    ENCODING = 'UTF8'
    LC_COLLATE = 'Italian_Italy.1252'
    LC_CTYPE = 'Italian_Italy.1252'
    TABLESPACE = pg_default
    CONNECTION LIMIT = -1;

    CREATE TABLE IF NOT EXISTS public.film
(
    codice integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    titolo character varying(25) COLLATE pg_catalog."default" NOT NULL,
    anno_produzione date NOT NULL,
    nazionalita character varying(25) COLLATE pg_catalog."default" NOT NULL,
    genere character varying(25) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT film_pkey PRIMARY KEY (codice)
)

CREATE TABLE IF NOT EXISTS public.sale
(
    codice integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    numero_posti integer NOT NULL,
    nome character varying(25) COLLATE pg_catalog."default" NOT NULL,
    citta character varying(25) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT sale_pkey PRIMARY KEY (codice)
)

CREATE TABLE IF NOT EXISTS public."cast"
(
    codice integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    nome character varying(25) COLLATE pg_catalog."default" NOT NULL,
    cognome character varying(25) COLLATE pg_catalog."default" NOT NULL,
    tipo character varying(25) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT cast_pkey PRIMARY KEY (codice)
)

CREATE TABLE IF NOT EXISTS public.proiezioni
(
    codice integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    codice_film integer NOT NULL,
    codice_sala integer NOT NULL,
    incasso double precision,
    data_proiezione date NOT NULL,
    CONSTRAINT proiezioni_pkey PRIMARY KEY (codice_film),
    CONSTRAINT fk_film FOREIGN KEY (codice_film)
        REFERENCES public.film (codice) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT fk_sala FOREIGN KEY (codice_sala)
        REFERENCES public.sale (codice) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

CREATE TABLE IF NOT EXISTS public.recita
(
    codice_attore integer NOT NULL,
    codice_film integer NOT NULL,
    CONSTRAINT recita_pkey PRIMARY KEY (codice_attore, codice_film),
    CONSTRAINT fk_cast FOREIGN KEY (codice_attore)
        REFERENCES public."cast" (codice) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT fk_film FOREIGN KEY (codice_film)
        REFERENCES public.film (codice) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)